#!/bin/bash

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

clear

echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║         SENSOR BACKEND MICROSERVICES ARCHITECTURE              ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}                    ┌─────────────────────┐${NC}"
echo -e "${YELLOW}                    │   ${GREEN}API Gateway${YELLOW}     │${NC}"
echo -e "${YELLOW}                    │   ${BLUE}Port: 8000${YELLOW}      │${NC}"
echo -e "${YELLOW}                    │   ${GREEN}✓ Circuit Breaker${YELLOW}│${NC}"
echo -e "${YELLOW}                    │   ${GREEN}✓ Load Balancing${YELLOW} │${NC}"
echo -e "${YELLOW}                    └──────────┬──────────┘${NC}"
echo -e "${YELLOW}                               │${NC}"
echo -e "${YELLOW}              ┌────────────────┼────────────────┐${NC}"
echo -e "${YELLOW}              │                │                │${NC}"
echo -e "${YELLOW}      ┌───────▼──────┐  ┌──────▼──────┐  ┌─────▼──────┐${NC}"
echo -e "${YELLOW}      │ ${GREEN}Auth Service${YELLOW} │  │ ${GREEN}Sensor Svc${YELLOW}  │  │ ${GREEN}Kafka Svc${YELLOW}  │${NC}"
echo -e "${YELLOW}      │ ${BLUE}Port: 8001${YELLOW}   │  │ ${BLUE}Port: 8002${YELLOW}  │  │ ${BLUE}Port: 8003${YELLOW} │${NC}"
echo -e "${YELLOW}      │ ${GREEN}✓ JWT Auth${YELLOW}   │  │ ${GREEN}✓ Testing${YELLOW}   │  │ ${GREEN}✓ Events${YELLOW}   │${NC}"
echo -e "${YELLOW}      │ ${GREEN}✓ Users${YELLOW}      │  │ ${GREEN}✓ Async${YELLOW}     │  │ ${GREEN}✓ Queue${YELLOW}    │${NC}"
echo -e "${YELLOW}      └──────┬───────┘  └──────┬──────┘  └─────┬──────┘${NC}"
echo -e "${YELLOW}             │                 │                │${NC}"
echo -e "${YELLOW}             └─────────────────┼────────────────┘${NC}"
echo -e "${YELLOW}                               │${NC}"
echo -e "${YELLOW}                    ┌──────────▼──────────┐${NC}"
echo -e "${YELLOW}                    │  ${GREEN}PostgreSQL DB${YELLOW}     │${NC}"
echo -e "${YELLOW}                    │  ${BLUE}Port: 5434${YELLOW}        │${NC}"
echo -e "${YELLOW}                    └─────────────────────┘${NC}"
echo ""

echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}RESILIENCE PATTERNS:${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}✓${NC} Circuit Breaker    - Prevents cascading failures"
echo -e "  ${GREEN}✓${NC} Graceful Degradation - System stays partially functional"
echo -e "  ${GREEN}✓${NC} Timeout & Retry    - Fast failure detection"
echo -e "  ${GREEN}✓${NC} Health Checks      - Automatic service discovery"
echo -e "  ${GREEN}✓${NC} Async Processing   - Non-blocking operations"
echo ""

echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}FAILURE SCENARIOS:${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${YELLOW}Scenario 1:${NC} Auth Service Down"
echo -e "    ${GREEN}→${NC} Sensor Service uses JWT fallback validation"
echo -e "    ${GREEN}→${NC} System continues working with degraded auth"
echo ""
echo -e "  ${YELLOW}Scenario 2:${NC} Kafka Service Down"
echo -e "    ${GREEN}→${NC} Events queued in memory"
echo -e "    ${GREEN}→${NC} Sensor tests complete successfully"
echo -e "    ${GREEN}→${NC} Events sent when Kafka recovers"
echo ""
echo -e "  ${YELLOW}Scenario 3:${NC} Database Down"
echo -e "    ${GREEN}→${NC} Services return 503 gracefully"
echo -e "    ${GREEN}→${NC} Circuit breaker opens"
echo -e "    ${GREEN}→${NC} No crashes or hanging requests"
echo ""
echo -e "  ${YELLOW}Scenario 4:${NC} Sensor Service Down"
echo -e "    ${GREEN}→${NC} Auth and Kafka continue working"
echo -e "    ${GREEN}→${NC} Gateway returns 503 for sensor endpoints"
echo -e "    ${GREEN}→${NC} Other endpoints unaffected"
echo ""

echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}QUICK COMMANDS:${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BLUE}Start all services:${NC}"
echo -e "    docker-compose -f docker-compose.microservices.yml up"
echo ""
echo -e "  ${BLUE}Check health:${NC}"
echo -e "    curl http://localhost:8000/health | jq '.'"
echo ""
echo -e "  ${BLUE}Test resilience:${NC}"
echo -e "    ./test_resilience.sh"
echo ""
echo -e "  ${BLUE}Scale a service:${NC}"
echo -e "    docker-compose up --scale sensor-service=3"
echo ""
echo -e "  ${BLUE}View logs:${NC}"
echo -e "    docker logs -f api-gateway"
echo ""

echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
